const CategoryData = [
  { image: '/all.jpeg', title: 'Icons' },
  { image: '/nature.jpeg', title: 'National Parks' },
  { image: '/beach.jpeg', title: 'Beach' },
  { image: '/design.jpeg', title: 'Design' },
  { image: '/cabns.jpeg', title: 'Cabins' },
  { image: '/tiny homes.jpeg', title: 'Tiny homes' },
  { image: '/luxe.jpeg', title: 'Luxe' },
  { image: '/countryside.jpeg', title: 'Countryside' },
  { image: '/camping.jpeg', title: 'Camping' },
  { image: '/pool.jpeg', title: 'Amazing pools'},
  { image: '/trending.jpeg', title: 'Trending'},
  { image: '/lake.jpeg', title: 'Lake'},
  { image: '/tree.jpeg', title: 'Treehouses'},
  { image: '/farms.jpeg', title: 'Farms'},
  { image: '/vineyards.jpeg', title: 'Vineyards'},
  { image: '/rooms.jpeg', title: 'Rooms'},
  { image: '/topcites.jpeg', title: 'Top cities'},
  { image: '/islands.jpeg', title: 'Islands'},
  { image: '/caves.jpeg', title: 'Caves'},
  { image: '/yurts.jpeg', title: 'Yurts'},
  { image: '/new.jpeg', title: 'New'},
  { image: '/ryokans.jpeg', title: 'Ryokans'},
  { image: '/grand.jpeg', title: 'Grand pianos'},
  { image: '/barns.jpeg', title: 'Barns'},
  { image: '/arctic.jpeg', title: 'Arctic'},
  { image: '/golfing.jpeg', title: 'Golfing'},
  { image: '/desert.jpeg', title: 'Desert'},
];


export default CategoryData;